#!/usr/bin/env bash
# Install haproxy and configure the load balancer

sudo apt-get -y update
sudo apt-get -y install haproxy

#configure HAproxy
cat << EOF > /etc/haproxy/haproxy.cfg
frontend http-in
        bind *:80
        default_backend servers
backend servers
        balance roundrobin
        server 116008-web-01 54.236.12.160:80 check
        server 116008-web-02 100.26.158.11:80 check
EOF

#Update hostname configuration
echo "54.236.12.160"> /etc/hostname
echo "100.26.158.11">> /etc/hostname

#Enable HAproxy init script
sudo sed -i 's/ENABLED=0/ENABLED=1/g' /etc/default/haproxy

#HAproxy starts
/etc/init.d/haproxy start
