#!/usr/bin/env bash
# Script for installing and seting up haproxy

apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-1.8
apt-get -y update
apt-get install -y haproxy=1.8.\*

echo "ENABLED=1" > /etc/default/haproxy

# Listen to web1 and web2 server
echo"
   listen load_balancer
   bind *:80
   mode http
   balance roundrobin
   option httpclose
   option forwardfor
   server 99567-web-01 100.25.110.60 check
   server 99567-web-02 100.26.11.33:80 check
" >> /etc/haproxy/haproxy.cfg

service haproxy start
